---
title: "Problem Set 1"
author: "Claire Jelison"
output: github_document
---

* * *

### Chapter 2 exercises

### Exercise 1 

1. For each of parts (a) through (d), indicate whether we would generally
expect the performance of a flexible statistical learning method to be
better or worse than an inflexible method. Justify your answer.

(a) The sample size n is extremely large, and the number of predictors p is small.
-Here, I think a flexible model is probably better than an inflexible. The large n relative to p means that we are unlikely to overfit the model based on a few outliers and are more likely to pick up an important trend. 

(b) The number of predictors p is extremely large, and the number
of observations n is small.
- Here, an inflexible model may be prefered since you run the risk of overfitting based on a limited amount of observation points. 

(c) The relationship between the predictors and response is highly
non-linear.
- Here, a more flexible model is likely necessary since a simple model would not account for the true relationship and the residuals would probably be bad. 

(d) The variance of the error terms, i.e. σ2 = Var(), is extremely
high.
- In this case, it is probably best to use an inflexible model since with high variance you are more likely to overfit. 

### Exercise 2
2. Explain whether each scenario is a classification or regression problem, and indicate whether we are most interested in inference or prediction. Finally, provide n and p.

(a) We collect a set of data on the top 500 firms in the US. For each
firm we record profit, number of employees, industry and the
CEO salary. We are interested in understanding which factors
affect CEO salary.
-Regression and inference. n = 500, p= 3 

(b) We are considering launching a new product and wish to know
whether it will be a success or a failure. We collect data on 20
similar products that were previously launched. For each product we have recorded whether it was a success or failure, price charged for the product, marketing budget, competition price,
and ten other variables.
-Classification and prediction. n = 20, p = 13 

(c) We are interest in predicting the % change in the USD/Euro(c) We are interest in predicting the % change in the USD/Euroexchange rate in relation to the weekly changes in the world
stock markets. Hence we collect weekly data for all of 2012. For
each week we record the % change in the USD/Euro, the %
change in the US market, the % change in the British market,
and the % change in the German market.
-Regression and prediction. n = weeks in a yr ~52 p = 4 

### Exercise 4
4. You will now think of some real-life applications for statistical learning.

(a) Describe three real-life applications in which classification might
be useful. Describe the response, as well as the predictors. Is the
goal of each application inference or prediction? Explain your
answer.
- You could try to predict whether a booking reservation is fraud by the days ahead it is booked, the email server the reservation came from, the time it was booked, and where it was booked. This is prediction cause you only care if it is fraud or not. 
-You could try to infer things about people from different states by the way they talk, how they dress, how they recreate, and what they like to eat as regressors. This is more inference because youre curious how chracteristics correspond to home state.
- You could try to predict whether someone will graduate high school by their grades, their test scores, their household income. This is prediction because you're primarily interested in guessing the right outcome. 


(b) Describe three real-life applications in which regression might
be useful. Describe the response, as well as the predictors. Is the
goal of each application inference or prediction? Explain your
answer.
- You could look at the effect of diet, exercise, and ethnicity on height. This is inference because you are curious how the predictors impact height. 
- You could look at the prices of houses using proximity to a school, number of bedrooms and bathrooms, crime in the area, closeness to a freeway, nearness to a park, and other factors. This is again inference because you are interested in the effect of the factors on a house's price. 
-You could try longevity based on diet, family history, medical history, social life, stress and other factors. Again, this is inference as you are curious to the effect of the regressors on the variable of interest. 

(c) Describe three real-life applications in which cluster analysis
might be useful.
- If you had the (x,y) coordinates of houses you could try to find cities through clustering. 
- I think you can use this method to explore personality traits by looking at where things tend to cluster like extroversion or introversion or assertiveness to determine what might be useful traits to look at further. 
- Maybe you could look at political polarization over time though clustering on data about certain views at the crossectional level and comparing k means to other periods in time. 

### Exercise 5
5. What are the advantages and disadvantages of a very flexible (versus
a less flexible) approach for regression or classification? Under what
circumstances might a more flexible approach be preferred to a less
flexible approach? When might a less flexible approach be preferred?
- A more flexible approach is good when you have a large n with less p, the data is very non linear or has clear breakpoints, there is very low variance in the data, the non linearity matches some kind of intuition you have about the data. 
_ A less flexibe model could be useful when you have a limited amount of observations or lots of regressors to look at, the data clearly appears to be linear, there is large variation in the data, lots of outliers, you are primarily looking for inference over correct prediciton. 

### Exercise 6 
6. Describe the differences between a parametric and a non-parametric
statistical learning approach. What are the advantages of a parametric approach to regression or classification (as opposed to a nonparametric approach)? What are its disadvantages?
- With a non parametric model essentially no assumptions about the true functional form of f are made as opposed to a parametric model. With a parametric model you generally need less observation points, however, the largest disadvantage is that the functional form you choose could be far from the true functional form. 



### Additional exercises

1) Using the notation standards described at the end of chapter one, please provide notation for the following objects:

**Input**: The 10 photos that we looked at on the first day, as if they were scanned at 64 x 64 pixel resolution.
input <- cbind(c(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10))
input

**Transformed Input**: The 10 photos, after a small number of features have been identified.
transformed = matrix(data, nrow = 10, ncol = pidfeatures)

**Output**: The associated actual ages of those 10 photos.
output <- c(23,45,24,45,65,23, 23,45,56,27)
Don't remeber the actual ages but order corresponds to order of photos. 

**Model**: Provide a guess at what (f) might look like (there is no single right answer here).
I think it could be modeled fairly linearly. 
f(x) = y int + b0(grayhair) + b1(wrinkles)
As grey hairness and wrinkleness increases age increases. 




